# Generated by Django 3.0.8 on 2021-01-23 17:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(db_column='datetime')),
                ('res', models.CharField(max_length=10)),
                ('stock_symbol', models.CharField(max_length=255)),
                ('open', models.DecimalField(decimal_places=2, max_digits=20)),
                ('close', models.DecimalField(decimal_places=2, max_digits=20)),
                ('low', models.DecimalField(decimal_places=2, max_digits=20)),
                ('high', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
        ),
        migrations.CreateModel(
            name='StrategySignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(db_column='datetime')),
                ('stock_symbol', models.CharField(max_length=255)),
                ('res', models.CharField(max_length=10)),
                ('stategy_name', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('signal', models.CharField(max_length=10)),
                ('score', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
