# Generated by Django 3.0.8 on 2021-01-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210124_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategysignal',
            old_name='stategy_name',
            new_name='strategy_name',
        ),
    ]
