# Generated by Django 3.0.8 on 2021-01-25 10:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210124_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to='')),
                ('parsed_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('policy_doc', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('name', models.CharField(max_length=1000)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
        ),
    ]
