# Generated by Django 3.0.8 on 2021-01-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_searchfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchfile',
            name='status',
            field=models.CharField(default='pending', max_length=1000),
        ),
    ]
