# Generated by Django 3.0.8 on 2021-01-30 07:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_searchfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchfile',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
